services:
  prometheus:
    deploy:
      placement:
        constraints:
          - ${PLACEMENT_CONSTRAINTS_NAME:-node.hostname} ${PLACEMENT_CONSTRAINTS_OPERATOR:-==} ${PLACEMENT_CONSTRAINTS_VALUE:-node}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.5}'
          memory: ${RESOURCES_LIMITS_MEMORY:-1G}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.1}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-512M}

volumes:
  data-vol:
    name: ${DATA_VOL_NAME}
    driver: ${VOL_DRIVER:-local}

configs:
  node_rules:
    name: ${NODE_RULES_NAME}
    file: ./rules/swarm_node.rules.dev.yml
