services:
  prometheus:
    deploy:
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-2G}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.1}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-512M}

volumes:
  data-vol:
    name: ${DATA_VOL_NAME}
    driver: ${PRO_VOL_DRIVER:-cloudstor:aws}
    driver_opts:
      backing: ${VOL_BACKING:-relocatable}
      size: ${VOL_SIZE:-10}
      ebstype: ${VOL_EBSTYPE:-gp2}

configs:
  node_rules:
    name: ${NODE_RULES_NAME}
    file: ./rules/swarm_node.rules.prod.yml
