version: '3.9'

services:
  prometheus:
    image: ${IMAGE_NAME:-prom/prometheus}:${IMAGE_TAG:-latest}
    entrypoint: ${CONFIG_PATH}/${ENTRYPOINT_FILENAME}
    command:
      - --config.file=${CONFIG_PATH}/${FINAL_CONFIG_FILENAME}
      - --storage.tsdb.path=${DATA_PATH}
      - --storage.tsdb.retention.time=${STORAGE_TSDB_RETENTION_TIME}
      - --storage.tsdb.retention.size=${STORAGE_TSDB_RETENTION_SIZE}
      - --web.external-url=https://${TRAEFIK_SUBDOMAIN}.${PUBLIC_HOSTNAME}
    environment:
      CONFIG_PATH:
      INITIAL_CONFIG_FILENAME:
      FINAL_CONFIG_FILENAME:
      JOBS:
    networks:
      metric-net:
      traefik-net:
    volumes:
      - data-vol:${DATA_PATH}
    configs:
      - source: entrypoint-config
        target: ${CONFIG_PATH}/${ENTRYPOINT_FILENAME}
        mode: 0555
      - source: prometheus-config
        target: ${CONFIG_PATH}/${INITIAL_CONFIG_FILENAME}
      - source: node_rules
        target: /etc/prometheus/swarm_node.rules.yml
      - source: service_rules
        target: /etc/prometheus/swarm_service.rules.yml
      - source: task_rules
        target: /etc/prometheus/swarm_task.rules.yml
      - source: scheduled_job_rules
        target: /etc/prometheus/scheduled_job.rules.yml
      - source: elasticsearch_rules
        target: /etc/prometheus/elasticsearch.rules.yml
      - source: kafka_rules
        target: /etc/prometheus/kafka.rules.yml
    healthcheck:
      test: wget --spider -q http://localhost:${PORT}
      interval: ${HEALTHCHECK_INTERVAL:-1m}
      timeout: ${HEALTHCHECK_TIMEOUT:-30s}
      retries: ${HEALTHCHECK_RETRIES:-10}
      start_period: ${HEALTHCHECK_START_PERIOD:-3m}
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-3s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      labels:
        traefik.enable: ${TRAEFIK_ENABLE:-true}
        traefik.http.routers.prometheus.entrypoints: ${TRAEFIK_ENTRYPOINT}
        traefik.http.routers.prometheus.rule: Host(`${TRAEFIK_SUBDOMAIN}.${PUBLIC_HOSTNAME}`)
        traefik.http.middlewares.prometheus-auth.basicauth.users: ${TRAEFIK_AUTH}
        traefik.http.routers.prometheus.middlewares: prometheus-auth
        traefik.http.services.prometheus.loadbalancer.server.port: ${PORT}

networks:
  metric-net:
    name: ${METRIC_NET_NAME:-metric-net}
    driver: ${METRIC_NET_DRIVER:-overlay}
    attachable: ${METRIC_NET_ATTACHABLE:-true}

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true

configs:
  entrypoint-config:
    name: ${ENTRYPOINT_CONFIG_NAME:-prometheus-entrypoint}
    file: ./conf/entrypoint.sh

  prometheus-config:
    name: ${PROMETHEUS_CONFIG_NAME:-prometheus-config}
    file: ./conf/prometheus.yml

  service_rules:
    name: ${SERVICE_RULES_NAME:-service_rules}
    file: ./rules/swarm_service.rules.yml

  task_rules:
    name: ${TASK_RULES_NAME:-task_rules}
    file: ./rules/swarm_task.rules.yml

  scheduled_job_rules:
    name: ${SCHEDULED_JOB_RULES_NAME:-scheduled_job_rules}
    file: ./rules/scheduled_job.rules.yml

  elasticsearch_rules:
    name: ${ELASTICSEARCH_RULES_NAME:-elasticsearch_rules}
    file: ./rules/elasticsearch.rules.yml

  kafka_rules:
    name: ${KAFKA_RULES_NAME:-kafka_rules}
    file: ./rules/kafka.rules.yml
