version: '3.9'

services:
  prometheus:
    deploy:
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.5}'
          memory: ${RESOURCES_LIMITS_MEMORY:-1G}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.1}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-256M}

volumes:
  data-vol:
    name: ${DATA_VOL_NAME}
    driver: local
    driver_opts:
      type: ${VOL_TYPE:-nfs4}
      o: addr=${VOL_ADDR:-127.0.0.1},${VOL_OPTS:-rw,nolock,noatime,tcp,rsize=8192,wsize=8192,timeo=14}
      device: ${DATA_VOL_DEVICE:-:/prometheus-vol/}

configs:
  node_rules:
    name: ${NODE_RULES_NAME}
    file: ./rules/swarm_node.rules.dev.yml
