version: '3.5'

services:
  prometheus:
    deploy:
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.5}'
          memory: ${RESOURCES_LIMITS_MEMORY:-1G}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.1}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-256M}

volumes:
  data-vol:
    name: ${DATA_VOL_NAME}

configs:
  node_rules:
    name: ${NODE_RULES_NAME}
    file: ./rules/swarm_node.rules.dev.yml
