groups:
- name: kafka
  rules:
  - record: kafka_consumer_lag_5m_sum_delta
    expr: sum(delta(kafka_consumergroup_lag_sum[5m]))

  - record: kafka_consumer_lag_5m_sum_delta_avg
    expr: avg_over_time(kafka_consumer_lag_5m_sum_delta[1d:])

  - record: kafka_consumer_lag_5m_sum_delta_stddev
    expr: stddev_over_time(kafka_consumer_lag_5m_sum_delta[1d:])

  - alert: KafkaConsumerLagIncreasing
    expr: abs(kafka_consumer_lag_5m_sum_delta - kafka_consumer_lag_5m_sum_delta_avg) / kafka_consumer_lag_5m_sum_delta_stddev > 1
    for: 3m
    labels:
      severity: warning
    annotations:
      description: abs(z-score) for lag of consumer group '{{$labels.consumergroup}}' is at {{$value | printf "%.3f"}} for '{{$labels.topic}}' topic
      summary: Consuming ratio of Kafka consumer group '{{$labels.consumergroup}}' is not enough for '{{$labels.topic}}' (abs(z-score > 1)

  - alert: KafkaConsumerTooHighLag
    expr: kafka_consumergroup_lag_sum > 1000000
    for: 1m
    labels:
      severity: critical
    annotations:
      description: Consumer group '{{$labels.consumergroup}}' has {{humanize $value}} pending messages from '{{$labels.topic}}' topic
      summary: Kafka consumers from '{{$labels.consumergroup}}' group are not consuming messages from '{{$labels.topic}}' (lag > 1M)
