groups:
- name: swarm_node
  rules:
  - alert: node_cpu_usage
    expr: 100 - (avg(irate(node_cpu_seconds_total{mode="idle"}[1m]) * ON(instance) GROUP_LEFT(node_name)
      node_meta * 100) BY (node_name)) > 90
    for: 5m
    labels:
      severity: warning
    annotations:
      description: Swarm node {{$labels.node_name}} CPU usage is at {{$value | printf "%.1f"}}%
      summary: CPU alert for Swarm node '{{$labels.node_name}}'

  - alert: node_memory_usage
    expr: sum(((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes)
      * ON(instance) GROUP_LEFT(node_name) node_meta * 100) BY (node_name) > 90
    for: 5m
    labels:
      severity: warning
    annotations:
      description: Swarm node {{$labels.node_name}} memory usage is at {{$value | printf "%.1f"}}%
      summary: Memory alert for Swarm node '{{$labels.node_name}}'

  - alert: node_disk_usage
    expr: ((node_filesystem_size_bytes{mountpoint!~"/var/lib/docker/.*"} -
      node_filesystem_free_bytes{mountpoint!~"/var/lib/docker/.*"}) * 100 /
      node_filesystem_size_bytes{mountpoint!~"/var/lib/docker/.*"}) *
      ON(instance) GROUP_LEFT(node_name) node_meta > 85
    for: 5m
    labels:
      severity: critical
    annotations:
      description: Swarm node {{$labels.node_name}} disk {{$labels.mountpoint}} usage is at {{$value | printf "%.1f"}}%
      summary: Disk '{{$labels.mountpoint}}' alert for Swarm node '{{$labels.node_name}}'

  - alert: node_disk_fill_rate_6h
    expr: predict_linear(node_filesystem_free_bytes{mountpoint!~"/var/lib/docker/.*"}[1h], 6 * 3600) *
      ON(instance) GROUP_LEFT(node_name) node_meta < 0
    for: 1h
    labels:
      severity: critical
    annotations:
      description: Swarm node {{$labels.node_name}} disk {{$labels.mountpoint}} is going to fill up in 6h
      summary: Disk '{{$labels.mountpoint}}' fill alert for Swarm node '{{$labels.node_name}}'

  - alert: SwarmNodeEbsDiskUsage
    expr: ((node_filesystem_size_bytes{mountpoint=~".*/ebs/.*"} - node_filesystem_free_bytes{mountpoint=~".*/ebs/.*"})
      * 100 / node_filesystem_size_bytes{mountpoint=~".*/ebs/.*"}) * ON(instance) GROUP_LEFT(node_name)
      node_meta > 85
    for: 5m
    labels:
      severity: critical
    annotations:
      description: Swarm node {{$labels.node_name}} EBS disk '{{$labels.mountpoint}}' usage is at {{$value | printf "%.1f"}}%
      summary: EBS disk alert for Swarm node '{{$labels.node_name}}'

  - alert: SwarmNodeEbsDiskFillRate
    expr: predict_linear(node_filesystem_free_bytes{mountpoint=~".*/ebs/.*"}[1h], 6 * 3600) * ON(instance)
      GROUP_LEFT(node_name) node_meta < 0
    for: 1h
    labels:
      severity: critical
    annotations:
      description: Swarm node {{$labels.node_name}} EBS disk '{{$labels.mountpoint}}' is going to fill up in 6h
      summary: EBS disk fill alert for Swarm node '{{$labels.node_name}}'
